package types


type AutoGenerated struct {
	ErrNo   int    `json:"err_no"`
	ErrMsg  string `json:"err_msg"`
	Data    []Data `json:"data"`
	Cursor  string `json:"cursor"`
	Count   int    `json:"count"`
	HasMore bool   `json:"has_more"`
}


type ArticleInfo struct {
	ArticleID      string  `json:"article_id"`
	UserID         string  `json:"user_id"`
	CategoryID     string  `json:"category_id"`
	TagIds         []int64 `json:"tag_ids"`
	VisibleLevel   int     `json:"visible_level"`
	LinkURL        string  `json:"link_url"`
	CoverImage     string  `json:"cover_image"`
	IsGfw          int     `json:"is_gfw"`
	Title          string  `json:"title"`
	BriefContent   string  `json:"brief_content"`
	IsEnglish      int     `json:"is_english"`
	IsOriginal     int     `json:"is_original"`
	UserIndex      int     `json:"user_index"`
	OriginalType   int     `json:"original_type"`
	OriginalAuthor string  `json:"original_author"`
	Content        string  `json:"content"`
	Ctime          string  `json:"ctime"`
	Mtime          string  `json:"mtime"`
	Rtime          string  `json:"rtime"`
	DraftID        string  `json:"draft_id"`
	ViewCount      int     `json:"view_count"`
	CollectCount   int     `json:"collect_count"`
	DiggCount      int     `json:"digg_count"`
	CommentCount   int     `json:"comment_count"`
	HotIndex       int     `json:"hot_index"`
	IsHot          int     `json:"is_hot"`
	RankIndex      float64 `json:"rank_index"`
	Status         int     `json:"status"`
	VerifyStatus   int     `json:"verify_status"`
	AuditStatus    int     `json:"audit_status"`
	MarkContent    string  `json:"mark_content"`
}

type University struct {
	UniversityID string `json:"university_id"`
	Name         string `json:"name"`
	Logo         string `json:"logo"`
}

type Major struct {
	MajorID  string `json:"major_id"`
	ParentID string `json:"parent_id"`
	Name     string `json:"name"`
}

type ExtraMap struct {
}

type AuthorUserInfo struct {
	UserID                  string     `json:"user_id"`
	UserName                string     `json:"user_name"`
	Company                 string     `json:"company"`
	JobTitle                string     `json:"job_title"`
	AvatarLarge             string     `json:"avatar_large"`
	Level                   int        `json:"level"`
	Description             string     `json:"description"`
	FolloweeCount           int        `json:"followee_count"`
	FollowerCount           int        `json:"follower_count"`
	PostArticleCount        int        `json:"post_article_count"`
	DiggArticleCount        int        `json:"digg_article_count"`
	GotDiggCount            int        `json:"got_digg_count"`
	GotViewCount            int        `json:"got_view_count"`
	PostShortmsgCount       int        `json:"post_shortmsg_count"`
	DiggShortmsgCount       int        `json:"digg_shortmsg_count"`
	Isfollowed              bool       `json:"isfollowed"`
	FavorableAuthor         int        `json:"favorable_author"`
	Power                   int        `json:"power"`
	StudyPoint              int        `json:"study_point"`
	University              University `json:"university"`
	Major                   Major      `json:"major"`
	StudentStatus           int        `json:"student_status"`
	SelectEventCount        int        `json:"select_event_count"`
	SelectOnlineCourseCount int        `json:"select_online_course_count"`
	Identity                int        `json:"identity"`
	IsSelectAnnual          bool       `json:"is_select_annual"`
	SelectAnnualRank        int        `json:"select_annual_rank"`
	AnnualListType          int        `json:"annual_list_type"`
	ExtraMap                ExtraMap   `json:"extraMap"`
	IsLogout                int        `json:"is_logout"`
}

type Category struct {
	CategoryID      string `json:"category_id"`
	CategoryName    string `json:"category_name"`
	CategoryURL     string `json:"category_url"`
	Rank            int    `json:"rank"`
	BackGround      string `json:"back_ground"`
	Icon            string `json:"icon"`
	Ctime           int    `json:"ctime"`
	Mtime           int    `json:"mtime"`
	ShowType        int    `json:"show_type"`
	ItemType        int    `json:"item_type"`
	PromoteTagCap   int    `json:"promote_tag_cap"`
	PromotePriority int    `json:"promote_priority"`
}

type Tags struct {
	ID               int    `json:"id"`
	TagID            string `json:"tag_id"`
	TagName          string `json:"tag_name"`
	Color            string `json:"color"`
	Icon             string `json:"icon"`
	BackGround       string `json:"back_ground"`
	ShowNavi         int    `json:"show_navi"`
	Ctime            int    `json:"ctime"`
	Mtime            int    `json:"mtime"`
	IDType           int    `json:"id_type"`
	TagAlias         string `json:"tag_alias"`
	PostArticleCount int    `json:"post_article_count"`
	ConcernUserCount int    `json:"concern_user_count"`
}

type UserInteract struct {
	ID        int64 `json:"id"`
	Omitempty int   `json:"omitempty"`
	UserID    int64 `json:"user_id"`
	IsDigg    bool  `json:"is_digg"`
	IsFollow  bool  `json:"is_follow"`
	IsCollect bool  `json:"is_collect"`
}

type Org struct {
	OrgInfo    interface{} `json:"org_info"`
	OrgUser    interface{} `json:"org_user"`
	IsFollowed bool        `json:"is_followed"`
}

type Status struct {
	PushStatus int `json:"push_status"`
}

type ResultModel struct {
	ArticleID      string         `json:"article_id"`
	ArticleInfo    ArticleInfo    `json:"article_info"`
	AuthorUserInfo AuthorUserInfo `json:"author_user_info"`
	Category       Category       `json:"category"`
	Tags           []Tags         `json:"tags"`
	UserInteract   UserInteract   `json:"user_interact"`
	Org            Org            `json:"org"`
	ReqID          string         `json:"req_id"`
	Status         Status         `json:"status"`
}

type Data struct {
	ResultType         int         `json:"result_type"`
	ResultModel        ResultModel `json:"result_model"`
	SearchAttachedInfo string      `json:"search_attached_info"`
}
